### ISSUE TITLE
Helllo Marek

### ISSUE THREAD

**Issue by SzymonMs** [marekfr/hello-git2#1]

**Comment by marekfr** [comment]
siema

**Comment by SzymonMs** [comment]
_Co tam?_

**Comment by D0minB** [comment]
Ale fajne zajęcia

**Comment by D0minB** [comment]
[NIE WCHODZIĆ](https://cdn.galleries.smcloud.net/t/galleries/gf-QZ7b-BZFD-8nYs_marcin-najman-memy-najlepsze-obrazki-ktore-komentuja-czekanie-boksera-664x442-nocrop.jpg)

**Comment by D0minB** [comment]
[10min](https://media.tenor.com/1GcAC8qPa_gAAAAM/najman-marcin.gif)

**Comment by DominikBogielczyk** [comment]
Browar po Zakrzewskim?
